- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      keypair: "insight_stylelend_key"
      group: "simple-group-1"
      instance_tag: "insight_project"
  tasks:
    - name: make one instance
      ec2:
        image: "ami-f4cc1de2" #standard ubuntu image
        instance_type: "t2.micro"
        keypair: "{{ keypair }}"
        instance_tags:
            Name: "{{ instance_tag }}"
        region: "us-east-1"
        group: "{{ group }}"
        wait: true
      register: ec2_info

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2_info.instances }}"
