---

- name: Provision a {{ application_name }} web server
  hosts: tag_Name_insight_project
  become: yes
  become_user: ubuntu
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - base_vars.yml

  vars_files:
    - vars.yml

  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"
