---
project_name: "wombat"
project_server_owner: "ubuntu"
project_server_group: "webapp"
system_packages:
  - git
  - nginx
  - gunicorn
  - postgresql
  - supervisor
  - postgresql-server-dev-all
  - python-pip
  - python-dev
  - python3-pip
  - python3-dev
  - python3-tk
  - python3-psycopg2

# db
db_user: "patrick"
db_name: "stylelend"
db_password: "pass"
db_host: localhost
db_port: 5432

# virtualenv
virtualenv_python_version: python3

# Project settings.
project_parent_dir: /home/ubuntu
project_path: "{{ project_parent_dir }}/{{ project_name }}"
webapp_path: "{{ project_path }}/{{ project_name }}/webapp"
virtualenv_path: "{{ project_path }}/.virtualenvs/{{ project_name }}"
log_dir: "{{ project_path }}/{{ project_name }}_logs"
supervisor_log_file: "{{ log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"

# Gunicorn settings.
gunicorn_user: "{{ project_server_owner }}"
gunicorn_group: "{{ project_server_owner }}"
gunicorn_log_file: "{{ log_dir }}/{{ project_name }}_gunicorn.log"
gunicorn_sock_file: "{{ project_path }}/{{ project_name }}_gunicorn.sock"

# Nginx settings.
nginx_access_log_file: "{{ log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ log_dir }}/nginx_error.log"
nginx_static_dir: "{{ webapp_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"
nginx_server_name: "{{ inventory_hostname }}"

# # Flask environment variables.
# flask_environment:
#   MEDIA_ROOT: "{{ nginx_media_dir }}"
#   STATIC_ROOT: "{{ nginx_static_dir }}"
#   DATABASE_NAME: "{{ db_name }}"
#   DATABASE_USER: "{{ db_user }}"
#   DATABASE_PASSWORD: "{{ db_password }}"
#   DATABASE_HOST: "{{ db_host }}"
#   DATABASE_PORT: "{{ db_port }}"
