---

- name: Install system packages
  apt: pkg={{ item }} update-cache=yes
  with_items: "{{ system_packages }}"

# - name: Clone git repo
#   git: repo="{{ git_repo }}"
#        dest="{{ project_path }}"
#        accept_hostkey=yes
#        version="{{ git_branch }}"
#        depth=1

- name: Run setup.py to setup Wombat as a module
  command: python3 setup.py develop
  args: 
    chdir: "{{ project_path  }}"
  run_once: true

- include: create_users_and_groups.yml
  tags: users_and_groups

- include: setup_virtualenv.yml
  tags: virtualenv

- include: set_file_permissions.yml
  tags: permissions

# - include: setup_flask_project.yml
#   tags: django

- include: setup_gunicorn.yml
  tags: gunicorn

- include: setup_nginx.yml
  tags: nginx

- include: setup_supervisor.yml
  tags: supervisor
