---

- name: Install system packages
  apt: pkg={{ item }} update-cache=yes
  with_items: "{{ system_packages }}"

# - name: Clone git repo
#   git: repo="{{ git_repo }}"
#        dest="{{ project_path }}"
#        accept_hostkey=yes
#        version="{{ git_branch }}"
#        depth=1

- name: Run setup.py to setup Wombat as a module
  command: "python3 {{ project_path  }}/setup.py develop"
  run_once: true

- include: create_users_and_groups.yml
  tags: users_and_groups

- include: setup_virtualenv.yml
  tags: virtualenv

# - name: Run create_db_tables.py to provision database
#   command: "{{ virtualenv_path }}/bin/activate && python3 {{ project_path  }}/wombat/bin/create_db_tables.py develop"

- include: set_file_permissions.yml
  tags: permissions

# - include: setup_flask_project.yml
#   tags: django

- include: setup_gunicorn.yml
  tags: gunicorn

- include: setup_nginx.yml
  tags: nginx

- include: setup_supervisor.yml
  tags: supervisor
