- name: Create the Nginx configuration file
  template: src=nginx.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the project site is enabled
  file: src=/etc/nginx/sites-available/{{ project_name }}
        dest=/etc/nginx/sites-enabled/{{ project_name }}
        state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
