- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Create the virtualenv
  command: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- name: Install packages required by the project inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
