---
- name: "Provision a {{ project_name }} site"
  hosts: tag_Name_wombat_ansible_test
  gather_facts: False
  remote_user: "{{ project_server_owner }}"
  become: true
  vars_files:
  - vars/base.yml
  - vars/production.yml

  pre_tasks:
  - name: Install python2
    raw: apt-get -y install python-simplejson

  roles:
  - db
  - web
