---
- name: "Provision a {{ application_name }} site"
  hosts: tag_Name_test
  gather_facts: False
  remote_user: "{{ server_user }}"
  become: true
  vars_files:
  - vars/base.yml
  - vars/production.yml

  pre_tasks:
  - name: Install python2
    raw: apt-get -y install python-simplejson

  roles:
  - db
  - web


